language: java

env:
  global:
    #GPG_PASS
    - secure: "QgHrSxYK24I8OIBw8WpKY+AJLxHUCMh0N8NdLJAslqPKsubYgEr+vo+ECB818T/UZnwAz+jlssc3HVcx8SqvGXPGwk65Sa9IozTaILBF8xt1gTN7sieDXAUVkoQhPVw5fXjmP6Kh0uAutZmDczaSGKx80Df+nLQrvFiBkTfXdOrYOBHE21C7V6UNA+K0NCVpuKubAzF5M+nOJNclKItJTJrKorbralXvP/+K4qlvNcQPAN5nUu0ivt22JFsH3rnGjHS0VAAbWYlHMtq98cVbSLGcW92Mu2yok6kZXmU/HO1vhcHgzcHPh8FejmM1I5DgxuoOjIpsnnXUc/p0yBfZYHcXgqgzb/DrH9eY97HVr2+eAGCSMLcapd4kHTQAEaQJH0DxOBJLrORInCM89HPDcdUj//MEZLG1wjOAcj65298uWhc+sY4mstKHwsgSe+pFhcaxD+P/fRCBPULoUWq/PK4Q97RKLPLYu8o7pj6Iqj9Mh89b1PX2uz/5SdoY6s/HpxzSswCszI+VHMvkKHnKim/YhFSicOKCHbE1rr766rGEAv5hV27PZDgzx2FgePwqMMyRIkmJG5UUOO9fSYh7XgLRasmFlXSQOwhQrVcE0QT12GiFLhMZZTdd/qA7P7sB6PReRfUpRf6suvrfFZmClt0RhX8iFbwJUZA8CXvDBLE="
    #OSSRH_USER
    - secure: "gFlhL9GJhiUzsWYJLiyM+3/a8tPt2Wbnw3g7vdtdF05MpZlHOxqy3++oIIDGmGXXA3cFp80oSTNC50N8wWNOerc0D+SLQK2aqNM0f5PzX6M4KAtoIXtZp44eWnji7cFwYqWPbRz/LtzSr2ttVL+1lBrMjyMHQMoc/j7WX8CaMoyLACoENesgS3uig2wtIHAk/D51jlpwLdq/Ufp69d4NgYBnJeHlT+2PNffPEv0gfEcKJSX8lrIw2bxCP77+HRXtrofFxd7L0Ypgwx3REelhISS0MI3bvjSSN0EHt6VklGniO9pZDlOVc4UpZFiSsl1UNmje8TIsYyDHBV+inJMdn8sCMn9xHZeujVH3WBe2j3b2bvwLn4IAM3F9QAhrBgmOefL4xCvdM3b59QhrzYiMc300RMicvPe5tGNK0X3ohP4d90K0jYBxsDfQXPh7T5vff1R5Yc03qVZi1P549w8t8IaY5RtUAk8XJ8MGoizriZf8sVy6SIcCjKB4FSUyjFlWKA5v0HIwaMolVBJS1uo6aJ00SFzNZ8GC4CAJ8An8lWN7UQWkw8w0UF+K0pezbHPtF2mfEALDTNnxnbdLCydOgikxJ7wjbaD6UWGYUups04XnzKVqV/a8BQXIx4lNn9QzOQpYxixZXn0feGpqncxlx2W77etx62sFIlQ8ox3kin0="
    #OSSRH_PASS
    - secure: "BR9KBvk8Mx5DFm7ypXl1J+jO+rOi36WMA/mIT04KLHjMPYCZIzeY7CD0kNMfEuUUIXPkqP2J1qvEjYnwjLqe3+zsHleXNaPbV5zhxik7gTFqo3qGUj6FDzFdSsBbZuj+0ZZ2qlAl+DWEiNfYS36178G7OQekl41slurOlDukQTzCFifm6ZDqKhtHF25m1/dKar9NxAho30Y0PGLEC8OhOIOHDplgrZhuX9Y61KdEhzh9SABpfYBPmkghveeyCenhk6IljFYi/JonIEbioDgz5ABUZv05PcbK4lKr5GZRzaEAbzjG4+IGoQM4ghmD5hz9xBTjpeEEU+noTcjwh5Gceg7Vxf60+h7ZaZhlZR/4nS0eJ0juf+O8KhndfNRpBWH+UPbI48gch9vTKS82T5F3NfSBBvMgb7224Ed5Hq+02jdvGteAI5VuYMUop/aICkvCDhhZFlakCGxVgNg8pHz9TgOBu6Nxtd0WO+jdEjnXhOOvmNpZX0sAimyYB7EktGe4lX+F8VEF2HNX1eJ4J/lH0KDvywNgs+Rd2LUP5okITKciZ0iuP/BETk4saWdHGdtA3OA6grtXwG0YPPXWl9TfPYWqk3dV0GHFZfNpC50WhBqSxiibSY9lDqCQFDJwDwltaqpvv1wLxjNbQFI4bqa3kn6tbDPJlRAnXgnr1FLSE30="

install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -P !build-extras -B

cache:
  directories:
    - ~/.m2/repository

after_success:
  - ./cd/deploy.sh
